# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ffc',
                'doc_host': 'https://fredguth.github.io',
                'git_url': 'https://github.com/fredguth/ffc',
                'lib_path': 'ffc'},
  'syms': {'ffc.core': {'ffc.core.foo': ('core.html#foo', 'ffc/core.py')}}}